name: Docker Build and Run

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and run Docker container
      run: |
        docker build -t logger .
        mkdir -p logs
        docker run -v $(pwd)/logs:/home/logs logger
        echo "1 -3 2" | docker run -i -v $(pwd)/logs:/home/logs logger solver

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: equation-logs
        path: logs/log.txt
