name: Docker Build and Run

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: docker build -t logger .
      
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run applications
      run: |
        docker run -v $(pwd)/logs:/home/logs logger
        echo "1 -3 2" | docker run -i -v $(pwd)/logs:/home/logs logger solver
        
    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: log-file
        path: logs/log.txt
